# Generated by Django 5.0.7 on 2024-08-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_remove_notification_text_notification_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_opened',
        ),
    ]
