# Generated by Django 5.0.6 on 2024-07-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, default='./profile_image/man.png', null=True, upload_to='profile_image'),
        ),
    ]
